### ISSUE TITLE
Create Kanban Board

### ISSUE THREAD

**Issue by principlebrothers** [hammaazarok/catalog-of-my-things#24]
## Description 
In this milestone we create kanban board and assign each team member a task

### Team Member
Below are the team members and GitHub account
- Team member 1 @principlebrothers 
- Team member 2 @ifzyy 
- Team member 3 @hammaazarok 

### Project Link
Below is the project link 
https://github.com/hammaazarok/catalog-of-my-things/projects/1

**Comment by HAMMAS-SALEEM** [comment]
# Required Changes :recycle:
![almost-there](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif)

## Hey Team(@principlebrothers, @hammaazarok, @ifzyy) :wave:

## Highlights :1st_place_medal:

:heavy_check_mark: Descriptive Issue Title
:heavy_check_mark: Using Github Issues Feature
:heavy_check_mark: Using Github Project Feature
:heavy_check_mark: Following some requirements

Good job on implementing some of the requirements, there are some issues that you still need to work on to go to the next project but you are almost there! :blush:

# Mandatory Requirements
![image](https://user-images.githubusercontent.com/93039359/194838515-c7580422-17c0-4a69-8e71-61faa29dd246.png)

- [ ] You have done a great job so far on creating your kanban board but i guess your forgot to assign some of the cards of the kanban board. Kindly assign these cards to any member of your group. These are group work cards so you can assign them to more than one member :blush:

- [ ] These unassigned cards has no descriptive title. Kindly make a descriptive title to all of them so you the reviewer would be able to understand what are you doing in this cards :+1:

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by thecodechaser** [comment]
## STATUS: APPROVED 🟢

## Hi @hammaazarok, @principlebrothers, and @ifzyy👋, 

Your project is complete!  There is nothing else to say other than... it's time to close it :shipit: 
Congratulations! 🎉 

<img src="https://media3.giphy.com/media/g9582DNuQppxC/giphy-downsized-medium.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
